{-# LANGUAGE ApplicativeDo       #-}
{-# LANGUAGE FlexibleContexts    #-}
{-# LANGUAGE NumericUnderscores  #-}
{-# LANGUAGE RecordWildCards     #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE FlexibleInstances   #-}
{-# LANGUAGE AllowAmbiguousTypes #-}
{-# OPTIONS_GHC -fno-warn-unused-top-binds #-} -- Unused things generated by `createDomain`
{-# OPTIONS_GHC -fno-warn-orphans #-} -- Unused things generated by `createDomain`

{-| Board-level orchestration of the Heron Core. Marries up control logic from
    `Heron.Core.Core` with its memory components.
-}
module Heron.Board
  (
  -- * Simulation
  sim
  -- * Full system
  , heronPE
  -- * Top-level synthesisable circuits
  , topEntity
  , topWithVIO
  , testBench
  ) where

import           Barbies.TH
import           Clash.Annotations.TH
import Clash.Cores.Xilinx.VIO
import           Clash.Explicit.Testbench
import           Clash.Prelude                         hiding (read)
import qualified Clash.Prelude.Testbench               as TB
import           Control.Lens                                 hiding (Index,
                                                               assign, at, imap,
                                                               op, (:>))
import           Data.Bifunctor (first)
import qualified Data.List                             as L
import           Data.Maybe                            (fromMaybe, isJust, fromJust)
import qualified Flite.TemplateSyntax                  as TS
import           Heron.Core.Collector
import           Heron.Core.Core
import           Heron.Core.Fifo
import           Heron.Core.Heap
import           Heron.Core.ParStack
import           Heron.Core.Stack
import           Heron.Core.Types
import           Heron.Encode                          (encProg)
import           Heron.External
import           Heron.Parameters
import           Heron.Primitives.DualPortRam
import qualified Heron.Primitives.ReadFirstDualPortRam as RF
import           Heron.Template
import           Heron.TemplateTH
import           Language.Haskell.TH                   hiding (Type)
import           RetroClash.Barbies

declareBareB [d|
  data PEIn = PEIn
    { peGo :: Maybe TemplAddr
    -- ^ Signal to start evaluation at given template address
    , peCode :: RamOp RomSize Template
    -- ^ Interface into code memory
    , peGcThreshold :: HeapAddr
    -- ^ GC triggering threshold
    } |]
deriving instance Generic (Pure PEIn)
deriving instance NFDataX (Pure PEIn)
deriving instance Show    (Pure PEIn)
deriving instance ShowX   (Pure PEIn)

declareBareB [d|
  data PEOut = PEOut
    { _peResult  :: Maybe Atom
    , _peStats   :: CPUStats
    } |]
makeLenses ''PEOut
deriving instance Generic (Pure PEOut)
deriving instance NFDataX (Pure PEOut)
deriving instance Show    (Pure PEOut)
deriving instance ShowX   (Pure PEOut)

type DebugState = (Pure CPUIn, Pure CPUOut, Pure GCIn, Pure GCOut)

-- | A complete processing element with large debug state exposed
heronPE
  :: forall dom
   . (HiddenClockResetEnable dom)
  => Signals dom PEIn
  -> (Signals dom PEOut, Signal dom DebugState)
heronPE PEIn{..} = (PEOut {..}, debug)
  where
    CPUOut{..} = cpu CPUIn{..}
    GCOut{..}  = gc GCIn{..}

    -- PE Outputs
    debug = bundle ( bundle CPUIn{..}, bundle CPUOut{..}
                   , bundle GCIn{..} , bundle GCOut{..}
                   )
    (_peStats, _peResult) = unbundle result
    result = regEn (unpack 0) goLatch _result

    -- Memory structure primitives
    uStkRam    = blockRam1 ClearOnReset (SNat @UStkSize) Nothing
    aStkRam    = blockRam1 ClearOnReset (SNat @AStkSize) Nothing
    pStkRam    = blockRam1 ClearOnReset (SNat @PStkSize) Nothing
    mutBufRam  = blockRam1 ClearOnReset (SNat @GCMutBufSize) Nothing
    heapRam = newHeap $ specialiseHeap heapConfig
                           (dpRam    @HeapSize @dom @HeapNode UltraRam   )
                           (RF.dpRam @HeapSize @dom @HeapNode RF.BlockRam)
    tmplRam = newHeap $    dpRam @RomSize  @dom @Template    BlockRam
    gcRam   = newHeap $ RF.dpRam @HeapSize @dom @GCNode   RF.BlockRam

    -- Memory instantiations
    -- * Dual-port RAMs
    heapIn  = heapRam heapOut'
    tmplIn  = head . read <$>  tmplRam tmplOut'
    gcMemIn = gcRam _gcMemOut
    -- * Stacks
    uStkIn = newStack uStkRam $ bundle (_uStkPush, _uStkPop)
    aStkIn = newStack aStkRam $ bundle (_aStkPush, _aStkPop)
    pStkIn = newStack pStkRam $ bundle (_pStkPush, _pStkPop)
    vStkIn = newCachedParStack _vStkOut _stkSnoopAddr
    updateIn = newFifo 0 mutBufRam (bundle (updatePush, _updatePop))

    -- Shared memory arbitration
    -- * Heap shared between mut, com, and gc
    (heapOut', gcAccess) = unbundle $ liftA2 arbitrateHeap _heapOut (maybe RamNoOp RamRead <$> _heapMemOut)
    -- * Code memory shared between mut and external interface
    tmplOut' = bundle $ (RamRead <$> _tmplOut) :> peCode :> Nil

    -- Additional mutator inputs
    goLatch = (isJust <$> peGo) .||. (isJust . snd) <$> _result
    begin  = let rootAtom = fmap (flip (Fun 0) True) <$> peGo
             in  regEn Nothing goLatch rootAtom
    gcCmd     = register NoCmd   _cmd
    nextAddrs = zipWith3 resolveNext
                  <$> fmap read gcMemIn
                  <*> register (repeat (Nothing,Nothing)) _nextFree
                  <*> fmap allocd request

    -- Additional collector inputs
    heapMemIn = mux (register False gcAccess)
                  (Just . head . read <$> heapIn)
                  (pure Nothing)
    bubble       = register False _allocBubble
    triggerThres = register 0     peGcThreshold
    request = register RNothing $
              TB.assert "ERROR: Mutator allocating after bubble prediction"
                ( (fold (||) . allocd <$> _gcRequest) .&&. bubble )
                ( pure False ) -- We can never say we're bubbling the mutator and then do an allocation!
                _gcRequest
    stkIn = bundle (size <$> vStkIn, head . _snoops <$> vStkIn)

    -- Mutation buffer helper
    updatePush = let updBarrier = gcCmd .==. pure UpdateBarrierCmd
                     hasUpdate  = isJust <$> _updateAddr
                     trigger    = register False (updBarrier .&&. hasUpdate)
                 in mux trigger
                      (Just . head . read <$> heapIn)
                      (pure Nothing)

    -- Allocation helpers
    resolveNext new current used = fromMaybe (tailPtr new)
                                             (if used then snd current else fst current)
    allocd (RAlloc as) = as
    allocd _           = repeat False

createDomain vSystem{vName="DomIn"  , vPeriod=  snatToNum (SNat @ClkT)}

type HeronIn = Signal DomIn
  ( "codeWE"   ::: Bool
  -- ^ Template memeory write enable
  , "codeAddr" ::: TemplAddr
  -- ^ Template memeory address
  , "codeData" ::: (BitVector (BitSize Template))
  -- ^ Template memeory data
  , "go"       ::: Bool
  -- ^ Start signal
  , "gcThres"  ::: HeapAddr
  )

type HeronOut = Signal DomIn
  ("ret"    ::: Atom
  ,"stats"  ::: CPUStats
  ,"retVld" ::: Bool
  )

-- | The main synthesisable system with explicit clock, resets, enables, and
-- port names.
topEntity
  :: "clk" ::: Clock DomIn
  -- ^ Input clock
  -> "rst" ::: Reset DomIn
  -- ^ Reset
  -> "en"  ::: Enable DomIn
  -- ^ Enable
  -> HeronIn
  -> HeronOut
  -- ^ Return result atom
topEntity clkIn rstIn enIn ins = reg defOut $ bundle
  ( fromMaybe (unpack 0) <$> _peResult peOut
  , _peStats peOut
  , isJust <$> _peResult peOut
  )
  where
    (cWe, cAddr, cData, go, gcThres) = unbundle $ reg defIns ins
    defIns = (False, 0, unpack 0, False, 0)
    reg :: NFDataX a => a -> Signal DomIn a -> Signal DomIn a
    reg d x = withClockResetEnable @DomIn clkIn rstIn enIn $ register d x

    defOut = (unpack 0 :: Atom, CPUStats 0 0 0 0, False)

    -- Register inputs
    cWe'     = reg False cWe
    cAddr'   = reg 0 cAddr
    cData'   = reg 0 cData
    go'      = withClockResetEnable @DomIn clkIn rstIn enIn (isRising False) $ reg False go
    gcThres' = reg 0 gcThres

    -- Transform to a `PEIn` record
    peIn = PEIn
      { peGo = mux go' (pure $ Just 0) (pure Nothing)
      , peCode = mux cWe' (RamWrite <$> cAddr' <*> fmap unpack cData')
                          (pure RamNoOp)
      , peGcThreshold = gcThres'
      }

    (peOut, _) = withClockResetEnable @DomIn clkIn rstIn enIn $
                   heronPE @DomIn peIn

{-# NOINLINE topEntity #-}
makeTopEntity 'topEntity

vioHeron
  :: BitSize Template <= 512 -- We pack templates into two 256 words for VIO
  => Clock DomIn
  -> HeronOut -> HeronIn
vioHeron clk = fmap mergeTmpl . vioProbe @DomIn ins outs defOut clk
  where
    mergeTmpl (cw,ca,cdLsb,cdMsb,go,gt) = (cw,ca, resize (cdMsb ++# cdLsb),go,gt)
    ins  = "ret" :> "stats" :> "retVld" :> Nil
    outs = "codeWE" :> "codeAddr" :> "codeDataLsb" :> "codeDataMsb" :> "go" :> "gcThres" :> Nil
    defOut  = (False, 0 :: Index RomSize, unpack 0 :: BitVector 256, unpack 0 :: BitVector 256, False, 0 :: HeapAddr)

topWithVIO
  :: "clk" ::: Clock DomIn
  -> "rst" ::: Reset DomIn
  -> "dummy" ::: Signal DomIn () -- Dummy output
topWithVIO clk rst = hwSeqX hOut (pure ())
  where
    en  = toEnable (pure True)
    hIn = vioHeron clk hOut
    hOut = topEntity clk rst en hIn

{-# NOINLINE topWithVIO #-}
makeTopEntity 'topWithVIO

simDropCycles :: Int
simDropCycles = 2 + (heapSize `div` 2)
  where
    heapSize = snatToNum (SNat @HeapSize)

simInputs :: TS.Prog -> [Pure PEIn]
simInputs p = L.concat
  [ L.zipWith (\a t -> defIn { peCode = RamWrite a t }) [0..] prog
  -- ^ Write each template
  , L.replicate (heapSize `div` 2 + 1 - L.length prog) defIn
  -- ^ Pause until GC has initialised
  , [defIn{ peGo = Just initAddr }]
  -- ^ Start reduction
  , L.repeat defIn
  -- ^ Wait
  ]
  where
    (initAddr, prog) = encProg p
    defIn :: Pure PEIn
    defIn = PEIn
      { peGo = Nothing
      , peCode = RamNoOp
      , peGcThreshold = defGcThreshold
      }
    heapSize = snatToNum (SNat @HeapSize)

simReport :: (debug -> String) -> [(Pure PEOut, debug)] -> IO (Int, CPUStats, Atom)
simReport showState simOut = do
  writeFile "/tmp/heron_sim.log" ""
  doneAt <- checkSamples $ L.zip [0::Integer ..] simOut
  case doneAt of
    Nothing  -> do
      error "Core still running... Aborting."
    Just idx -> do putStrLn $ L.concat ["Finished after ", show (idx-1), " cycles: "]
                   let final = fst $ simOut L.!! idx
                   let ans   = fromJust $ _peResult final
                   pure (idx - 1, _peStats final, ans)
  where
    checkSamples [] = pure Nothing
    checkSamples ((i,s):ss) = do
      appendFile "/tmp/heron_sim.log" ("Cycle " L.++ show i L.++ "===================")
      appendFile "/tmp/heron_sim.log" (showState $ snd s)
      if isJust . _peResult $ fst s
        then pure . Just $ fromIntegral i
        else checkSamples ss

simDUT
  :: forall dom debug
   . (KnownDomain dom, NFDataX debug)
  => Int
  -- ^ Bound on cycle count before termination (pass `maxBound` for maximumg)
  -> (Signals dom PEIn -> (Signals dom PEOut, Signal dom debug))
  -- ^ Design under test
  -> TS.Prog
  -- ^ Input program as F-lite templates
  -> IO [(Pure PEOut, debug)]
  -- ^ Output samples
simDUT limit dut p =
  let inps = unbundle . fromList $ simInputs p
      hw   = bundle $ first bundle $ dut inps
  in pure (L.take limit $
           L.drop simDropCycles $
           sample hw)

-- | Simulate `heronPE` at a Haskell-level
sim :: Int
    -- ^ Bound on cycle count before termination (pass `maxBound` for maximum)
    -> TS.Prog
    -- ^ Input program as F-lite templates
    -> IO (Int, CPUStats, Atom)
    -- ^ (Simulated cycle count, stats, return value)
sim limit p = simDUT limit dut p >>= simReport showPEState
  where dut = exposeClockResetEnable heronPE
                systemClockGen systemResetGen enableGen

  -- Report results

showPEState :: DebugState -> String
showPEState (is, os, gis, gos) = L.unlines
  [ "Stk top   : " L.++ showX (read (vStkIn is))
  , "Heap Ctrls: " L.++ showX  (_heapOut os)
  , "Result    : " L.++ showX (snd $ _result os)
  , "Stats     : " L.++ showX (fst $ _result os)
  , "AStk top  : " L.++ showX (read (aStkIn is))
  , "Outs      : " L.++ showX os
  , "Ins       : " L.++ showX is
  , "GC Ins    : " L.++ showX gis
  , "GC Outs   : " L.++ showX gos
  ]

defGcThreshold :: HeapAddr
defGcThreshold = perc d47
  where
    perc x = snatToNum $
             divSNat (mulSNat x (SNat @(HeapSize `Div` 4)))
                     d100

-- | Simulate `topEntity` at a verilog-level. Uses Clash's `outputVerifier'` to
-- produce a verilog testbench. Assertion errors will be thrown if answer is
-- wrong, too early, or too late.
--
-- For now, this is specialised to only one benchmark using Template Haskell.
testBench :: Signal DomIn Bool
testBench = done
 where
  -- Use Template Haskell to run C emulator and return benchmark's
  -- expected cycles (as type-level Nat), expected return atom,
  -- and it's compiled templates (as a Vec)
  (expCycles, expAtom, tmpls)
            = $( do prog <- runIO $ getProjectFile "tests/benchmarks/adjoxo.fl" >>= compileBenchmark
                    let code = snd (encProg prog)
                    tmplsVec <- listToVecTH code
                    (emuRet, emuCycles) <- runIO (runEmulator prog)
                    emuRetAtom <- [| PrimInt emuRet |]
                    emuCyclesS <- promoteIntTH emuCycles
                    let tup = TupE [Just emuCyclesS, Just emuRetAtom, Just tmplsVec]
                    return tup
               )

  tmplNoOp = (False, 0, unpack minBound)
  testInput = unzip $ replicate d30 (tmplNoOp, False) ++
                      -- Wait for enable/reset
                      zipWith (\t a -> ((True, a, t), False)) tmpls (iterateI (+1) 0) ++
                      -- Write templates
                      -- replicate (SNat @(HeapSize `Div` 2)) (tmplNoOp, False) ++
                      -- Wait for GC memory to initialise
                      singleton (tmplNoOp, True) ++
                      singleton (tmplNoOp, False)

  (tmplWe, tmplAddr, tmplData)
     = unbundle $ stimuliGenerator clkIn rstIn (fst testInput)
  tmplBits = fmap pack tmplData
  go = stimuliGenerator clkIn rstIn (snd testInput)
  gcThres = pure defGcThreshold

  done = withClockResetEnable clkIn rstIn enIn assertReturn expCycles expAtom .
         unbundle . topEntity clkIn rstIn enIn $ bundle (tmplWe, tmplAddr, tmplBits, go, gcThres)

  enIn           = enableGen  @DomIn
  clkIn          = tbClockGen @DomIn (fmap not done)
  rstIn          = resetGen   @DomIn

assertReturn
  :: HiddenClockResetEnable dom
  => SNat n
  -> Atom
  -> (Signal dom Atom, Signal dom CPUStats, Signal dom Bool)
  -> Signal dom Bool
assertReturn lim ans (ret, s, vld) =
  TB.assert "FAIL: BAD RETURN VALUE"
    (pure ans .==. ret)
    end
    (delay False end)
  where
    muts = _mutCycles <$> s
    -- Finishing correctly only counts when we report the expected mutator
    -- cycles too
    finished = vld .&&. muts .==. pure (snatToNum lim)
    -- Timeout after initialisation time + twice the expected mutator cycles.
    timeOut = riseEvery $ addSNat (SNat @(HeapSize `Div` 2)) $
                          mulSNat d2 lim
    end = timeOut .||. finished
