{-# LANGUAGE AllowAmbiguousTypes  #-}
{-# LANGUAGE ApplicativeDo        #-}
{-# LANGUAGE FlexibleContexts     #-}
{-# LANGUAGE FlexibleInstances    #-}
{-# LANGUAGE LambdaCase           #-}
{-# LANGUAGE NumericUnderscores   #-}
{-# LANGUAGE RecordWildCards      #-}
{-# LANGUAGE ScopedTypeVariables  #-}
{-# LANGUAGE UndecidableInstances #-}
{-# OPTIONS_GHC -fno-warn-unused-top-binds #-} -- Unused things generated by `createDomain`
{-# OPTIONS_GHC -fno-warn-orphans #-} -- Unused things generated by `createDomain`

{-| Board-level orchestration of the Heron Core. Marries up control logic from
    `Heron.Core.Core` with its memory components.
-}
module Heron.Board
  (
  -- * Full systems
    heronSingleCore
  , heronMesh
  -- * Top-level synthesisable circuits
  , topEntity
  , topWithVIO
  -- , testBench
  ) where

import           Clash.Annotations.TH
import           Clash.Cores.Xilinx.VIO
import qualified Clash.Explicit.Prelude   as E
import           Clash.Explicit.Testbench
import           Clash.Prelude            hiding (read)
import qualified Clash.Prelude.Testbench  as TB
import           Data.Maybe               (fromMaybe, isJust)
import           Heron.Core.Core
import           Heron.Encode             (encProg)
import           Heron.Error
import           Heron.External
import           Heron.Mesh
import           Heron.Parameters
import           Heron.PE
import           Heron.Schedule.Types     (Workload (..))
import           Heron.Template
import           Heron.TemplateTH
import           Language.Haskell.TH      hiding (Type)
import           RetroClash.Barbies

--------------------------------------------------------------------------------
-- Top level synthesisable circuits

-- | A complete 2D mesh system built from Heron PEs
heronMesh
  :: forall cols rows slrs
   . (HiddenClockResetEnable DomIn, KnownNat cols, KnownNat rows, KnownNat slrs)
  => SNat (cols+1)
  -> SNat (rows+1)
  -> SNat (slrs+1)
  -> Signals DomIn PEIn
  -> Signals DomIn PEOut
heronMesh x y slrs PEIn{..} = PEOut {..}
  where
    (_, _, _, _, _peResult, _peStats) = genSuperMesh slrs peGo peRelease peCode peGcThreshold nullColRxs nullRowRxs nullColRxs nullRowRxs
    nullRowRxs = replicate (mulSNat slrs y) nullRx
    nullColRxs = replicate x nullRx
    _pePortsTx = bundle $ repeat nullTx
    nullRx = pure $ PortRx Nothing False $ Workload (0,0) 0 0
    nullTx = pure $ PortTx Nothing False $ Workload (0,0) 0 0

-- Top-level circuits

type HeronIn = Signal DomIn
  ( "codeWE"   ::: Bool
  -- ^ Template memeory write enable
  , "codeAddr" ::: TemplAddr
  -- ^ Template memeory address
  , "codeData" ::: BitVector (BitSize Template)
  -- ^ Template memeory data
  , "go"       ::: Bool
  -- ^ Start signal
  , "unlock"  ::: Bool
  -- ^ Allow PEs to start evaluation
  , "gcThres"  ::: HeapAddr
  -- ^ GC Threshold
  )

type HeronOut = Signal DomIn
  ("ret"    ::: Either Err Atom
  -- ^ Return value
  ,"stats"  ::: CPUStats
  -- ^ Clock cycle stats
  ,"retVld" ::: Bool
  -- ^ Return value valid
  )

-- | The main synthesisable system with explicit clock, resets, enables, and
-- port names.
topEntity
  :: "clk" ::: Clock DomIn
  -- ^ Input clock
  -> "rst" ::: Reset DomIn
  -- ^ Reset
  -> "en"  ::: Enable DomIn
  -- ^ Enable
  -> HeronIn
  -> HeronOut
topEntity clkIn rstIn _enIn ins = reg defOut $ bundle
  ( fromMaybe (unpack 0) <$> _peResult peOut
  , _peStats peOut
  , isJust <$> _peResult peOut
  )
  where
    (cWe, cAddr, cData, go, unlock, gcThres) = unbundle $ reg defIn ins
    reg :: NFDataX a => a -> Signal DomIn a -> Signal DomIn a
    reg d x = withClockResetEnable @DomIn clkIn rstIn en $ register d x

    defOut = (unpack 0 :: Either Err Atom, CPUStats 0 0 0 0 0, False)
    defIn  = (False, 0, unpack 0, False, False, 0)

    -- Register inputs
    cWe'     = reg False cWe
    cAddr'   = reg 0 cAddr
    cData'   = reg 0 cData
    go'      = reg False go
    unlock' = reg False unlock
    gcThres' = reg 0 gcThres

    -- Transform to a `PEIn` record
    peIn = PEIn
      { peGo = mux go' (pure $ Just 0) (pure Nothing)
      , peRelease = unlock'
      , peCode = mux cWe' (RamWrite <$> cAddr' <*> fmap unpack cData')
                          (pure RamNoOp)
      , peGcThreshold = gcThres'
      , pePortsRx = pure (repeat (PortRx Nothing False $ Workload (0,0) 0 0))
      , peId = pure (0,0)
      }

    meshX = SNat @MeshCols
    meshY = SNat @MeshRows
    meshZ = SNat @Meshes
    en = toEnable $ pure True
    peOut = withClockResetEnable @DomIn clkIn rstIn en $
            -- heronSingleCore peIn
            heronMesh meshX meshY meshZ peIn

{-# NOINLINE topEntity #-}
makeTopEntity 'topEntity

vioHeron
  :: BitSize Template <= 512 -- We pack templates into two 256 words for VIO
  => Clock DomIn
  -> HeronOut -> HeronIn
vioHeron clk = fmap mergeTmpl . vioProbe @DomIn ins outs defOut clk
  where
    mergeTmpl (cw,ca,cdLsb,cdMsb,go,rel,gt) = (cw,ca, resize (cdMsb ++# cdLsb),go,rel,gt)
    ins  = "ret" :> "stats" :> "retVld" :> Nil
    outs = "codeWE" :> "codeAddr" :> "codeDataLsb" :> "codeDataMsb" :> "go" :> "unlock" :> "gcThres" :> Nil
    defOut = (False, 0 :: Index RomSize, unpack 0 :: BitVector 256, unpack 0 :: BitVector 256, False, False, 0 :: HeapAddr)

-- A wrapper for topEntity that exposes I/O via Xilinx VIO
topWithVIO
  :: "clk" ::: Clock DomIn
  -> "rst" ::: Reset DomIn
  -> "dummy" ::: Signal DomIn () -- Dummy output
topWithVIO clk rst = hwSeqX hOut (pure ())
  where
    en  = toEnable (pure True)
    hIn = vioHeron clk hOut
    hOut = topEntity clk rst en hIn

{-# NOINLINE topWithVIO #-}
makeTopEntity 'topWithVIO

{-
-- | Simulate `topEntity` at a verilog-level. Uses Clash's `outputVerifier'` to
-- produce a verilog testbench. Assertion errors will be thrown if answer is
-- wrong, too early, or too late.
--
-- For now, this is specialised to only one benchmark using Template Haskell.
testBench :: Signal DomIn Bool
testBench = done
 where
  -- Use Template Haskell to run C emulator and return benchmark's
  -- expected cycles (as type-level Nat), expected return atom,
  -- and it's compiled templates (as a Vec)
  (expCycles, expAtom, tmpls)
            = $( do prog <- runIO $ getProjectFile "tests/benchmarks/par/tak.fl" >>= compileBenchmark
                    let code = snd (encProg prog)
                    tmplsVec <- listToVecTH code
                    (emuRet, emuCycles) <- runIO (runEmulator prog)
                    emuRetAtom <- [| PrimInt emuRet |]
                    emuCyclesS <- promoteIntTH emuCycles
                    let tup = TupE [Just emuCyclesS, Just emuRetAtom, Just tmplsVec]
                    return tup
               )

  tmplNoOp = (False, 0, unpack minBound)
  testInput = unzip $ replicate d30 (tmplNoOp, False) ++
                      -- Wait for enable/reset
                      zipWith (\t a -> ((True, a, t), False)) tmpls (iterateI (+1) 0) ++
                      -- Write templates
                      -- replicate (SNat @(HeapSize `Div` 2)) (tmplNoOp, False) ++
                      -- Wait for GC memory to initialise
                      singleton (tmplNoOp, True) ++
                      singleton (tmplNoOp, False)

  (tmplWe, tmplAddr, tmplData)
     = unbundle $ stimuliGenerator clkIn rstIn (fst testInput)
  tmplBits = fmap pack tmplData
  go = stimuliGenerator clkIn rstIn (snd testInput)
  gcThres = pure defGcThreshold

  done = withClockResetEnable clkIn rstIn enIn assertReturn expCycles expAtom .
         unbundle . topEntity clkIn rstIn enIn $ bundle (tmplWe, tmplAddr, tmplBits, go, gcThres)

  enIn           = enableGen  @DomIn
  clkIn          = tbClockGen @DomIn (fmap not done)
  rstIn          = resetGen   @DomIn
-}

assertReturn
  :: HiddenClockResetEnable dom
  => SNat n
  -> Atom
  -> (Signal dom (Either Err Atom), Signal dom CPUStats, Signal dom Bool)
  -> Signal dom Bool
assertReturn lim ans (ret, s, vld) =
  TB.assert "FAIL: BAD RETURN VALUE"
    (pure (Right ans) .==. ret)
    end
    (register False end)
  where
    muts = _mutCycles <$> s
    -- Finishing correctly only counts when we report the expected mutator
    -- cycles too
    finished = vld .&&. muts .==. pure (snatToNum lim)
    -- Timeout after initialisation time + twice the expected mutator cycles.
    timeOut = riseEvery $ addSNat (SNat @(HeapSize `Div` 2)) $
                          mulSNat d2 lim
    end = timeOut .||. finished

defGcThreshold :: HeapAddr
defGcThreshold = perc d47
  where
    perc x = snatToNum $
             divSNat (mulSNat x (SNat @(HeapSize `Div` 4)))
                     d100
