{-# LANGUAGE AllowAmbiguousTypes  #-}
{-# LANGUAGE ApplicativeDo        #-}
{-# LANGUAGE FlexibleContexts     #-}
{-# LANGUAGE FlexibleInstances    #-}
{-# LANGUAGE RecordWildCards      #-}
{-# LANGUAGE ScopedTypeVariables  #-}
{-# LANGUAGE UndecidableInstances #-}
{-# OPTIONS_GHC -fno-warn-unused-top-binds #-} -- Unused things generated by `createDomain`
{-# OPTIONS_GHC -fno-warn-orphans #-} -- Unused things generated by `createDomain`

module Heron.Mesh
  ( genMesh
  , genSuperMesh
  ) where

import           Clash.Prelude        hiding (read)
import           Data.Proxy
import           Data.Singletons      (Apply, TyFun, type (@@))
import           Heron.Core.Core
import           Heron.Core.Fifo
import           Heron.Core.Types
import           Heron.Error
import           Heron.Parameters
import           Heron.PE
import           Heron.Schedule.Types (Workload (..))
import           Heron.Template

type PERet = Maybe (Either Err Atom)

type PE dom
  =  Index MaxPECols -- ^ Core ID's x coord
  -> Index MaxPERows -- ^ Core ID's y coord
  -> Vec 4 (Signal dom PortRx) -- ^ Read ports from neighbours
  -> Vec 4 (Signal dom PortTx) -- ^ Write ports to neighbours

type PERow dom n
  =  Index MaxPERows -- ^ Row's y coord
  ->    Vec n (Signal dom PortRx) -- ^ Read ports from above
     -> Signal dom PortRx         -- ^ Read port from right
     -> Vec n (Signal dom PortRx) -- ^ Read ports from below
     -> Signal dom PortRx         -- ^ Read port from left
  -> ( Vec n (Signal dom PortTx)  -- ^ Write ports to above
     , Signal dom PortTx          -- ^ Write port to right
     , Vec n (Signal dom PortTx)  -- ^ Write ports to below
     , Signal dom PortTx          -- ^ Write port to left
     , Signal dom PERet           -- ^ Result from row's head
     , Signal dom CPUStats        -- ^ Stats from row's head
     )

type PEMesh dom n m
  =  Vec n (Signal dom PortRx)
  -> Vec m (Signal dom PortRx)
  -> Vec n (Signal dom PortRx)
  -> Vec m (Signal dom PortRx)
  -> ( Vec n (Signal dom PortTx)
     , Vec m (Signal dom PortTx)
     , Vec n (Signal dom PortTx)
     , Vec m (Signal dom PortTx)
     , Signal dom PERet
     , Signal dom CPUStats
     )

-- Prepare a motive for dependently typed fold for appending PE onto a PERow
data AppendPE (a :: Domain) (f :: TyFun Nat Type) :: Type
type instance Apply (AppendPE a) l = PERow a (1+l)
data AppendPERow (a :: Domain) (n :: Nat) (f :: TyFun Nat Type) :: Type
type instance Apply (AppendPERow a n) l = PEMesh a n (1+l)
data AppendMesh (a :: Domain) (n :: Nat) (m :: Nat) (f :: TyFun Nat Type) :: Type
type instance Apply (AppendMesh a n m) l = PEMesh a n ((1+l)*m)

genRow
  :: forall n
   . (HiddenClockResetEnable DomIn, KnownNat n)
  => Signal DomIn (Index MaxPERows)        -- ^ Y-offset for this submesh
  -> Signal DomIn (Maybe TemplAddr)        -- ^ Root PE Go signal
  -> Signal DomIn Bool                     -- ^ Release signal
  -> Signal DomIn (RamOp RomSize Template) -- ^ PE Code
  -> Signal DomIn HeapAddr                 -- ^ GC Threshold
  -> PERow DomIn (n+1)
genRow yOffset go unlock code gcThres = dfold m appendPE singletonRow (repeat pe)
  where
  m = Proxy :: Proxy (AppendPE DomIn)

  -- A master PE that accepts external `go` and reports its final results/stats
  singletonRow :: AppendPE DomIn @@ 0
  singletonRow y us r ds l =
    let heronPEInst = heronPE $ PEIn
          { peGo = go
          , peRelease = unlock
          , peCode = code
          , peGcThreshold = gcThres
          , pePortsRx = bundle (head us :> r :> head ds :> l :> Nil)
          , peId = bundle (pure 0, (+y) <$> yOffset)
          }
        PEOut {..} = heronPEInst
        -- ^ We have the seperate binding to retain the `heronPEInst` name in the verilog output
        (u':>r':>d':>l':>Nil) = unbundle _pePortsTx
    in  (singleton u', r', singleton d', l' , _peResult, _peStats)

  -- This generic PE as no external `go` signal and copies the master's code and gc threshold signals
  pe :: PE DomIn
  pe x y rx = let heronPEInst = heronPE $ PEIn
                    { peGo = pure Nothing
                    , peRelease = last $ iterate (SNat @MaxPECols) (register False) unlock
                    , peCode = last $ iterate (SNat @MaxPECols) (register RamNoOp) code
                    , peGcThreshold = last $ iterate (SNat @MaxPECols) (register 0) gcThres
                    , pePortsRx = bundle rx
                    , peId = bundle (pure x, (+y) <$> yOffset)
                    }
                  PEOut {..} = heronPEInst
              in unbundle _pePortsTx

-- Append a single PE onto the right of a PERow
appendPE :: forall dom l .
           (HiddenClockResetEnable dom)
        => SNat l -> PE dom -> PERow dom (l+1) -> PERow dom (l+2)
appendPE x n ns y usRx rRx dsRx lRx = (usTx, rTx, dsTx, lTx, ret, stats)
  where
    -- Apply to PERow
    (rowUsTx, rowRTx, rowDsTx, rowLTx, ret, stats) =
      ns y (init usRx) endRx (init dsRx) lRx

    -- Apply to new PE
    (endRx, newRx) = portConnector rowRTx newLTx
    (newUTx :> newRTx :> newDTx :> newLTx:> Nil) =
      n (snatToNum x + 1) y (last usRx :> rRx :> last dsRx :> newRx :> Nil)

    -- Collect for top level
    (usTx, rTx, dsTx, lTx) = ( rowUsTx ++ singleton newUTx
                             , newRTx
                             , rowDsTx ++ singleton newDTx
                             , rowLTx
                             )

-- Append a row of PEs onto the bottom of a PEMesh
appendPERow
  :: forall dom l n
   . (HiddenClockResetEnable dom)
  => SNat l -> PERow dom n -> PEMesh dom n (l+1) -> PEMesh dom n (l+2)
appendPERow y n ns usRx rsRx dsRx lsRx = (usTx, rsTx, dsTx, lsTx, ret, stats)
  where
    -- Apply to mesh
    (meshUsTx, meshRsTx, meshDsTx, meshLsTx, ret, stats) =
      ns usRx (init rsRx) endsRx (init lsRx)

    -- Apply to new row
    (endsRx, newsRx) =
      unzip $ zipWith portConnector meshDsTx newUsTx
    (newUsTx, newRTx, newDsTx, newLTx, _, _) =
      n (snatToNum y + 1) newsRx (last rsRx) dsRx (last lsRx)

    -- Collect for top level
    (usTx, rsTx, dsTx, lsTx) =
      ( meshUsTx
      , meshRsTx ++ singleton newRTx
      , newDsTx
      , meshLsTx ++ singleton newLTx
      )

genMesh
  :: forall n m
   . (HiddenClockResetEnable DomIn, KnownNat n, KnownNat m)
  => Signal DomIn (Index MaxPERows) -- ^ Y-offset for this submesh
  -> Signal DomIn (Maybe TemplAddr) -- ^ Root PE Go signal
  -> Signal DomIn Bool -- ^ Release signal
  -> Signal DomIn (RamOp RomSize Template) -- ^ PE Code
  -> Signal DomIn HeapAddr -- ^ GC Threshold
  -> PEMesh DomIn (n+1) (m+1)
genMesh yOffset go unlock code gcThres = dfold m appendPERow singletonMesh (repeat row)
  where
  m = Proxy :: Proxy (AppendPERow DomIn (n+1))

  -- A master PE that accepts external `go` and reports its final results/stats
  singletonMesh :: AppendPERow DomIn (n+1) @@ 0
  singletonMesh us rs ds ls =
    let (us', r', ds', l', ret, stats) = genRow yOffset go unlock code gcThres 0 us (head rs) ds (head ls)
    in  (us', singleton r', ds', singleton l', ret, stats)

  -- This generic PE row is a slave
  row :: PERow DomIn (n+1)
  row = genRow yOffset (pure Nothing) dRelease dCode dGcThreshold
  dRelease = last $ iterate (SNat @MaxPECols) (register False) unlock
  dCode = last $ iterate (SNat @MaxPECols) (register RamNoOp) code
  dGcThreshold = last $ iterate (SNat @MaxPECols) (register 0) gcThres

portConnector
  :: HiddenClockResetEnable dom
  => Signal dom PortTx -> Signal dom PortTx -> (Signal dom PortRx, Signal dom PortRx)
portConnector atx btx = (arx, brx)
  where
    portRam = blockRam1 ClearOnReset (SNat @PortBufSize) Nothing

    abFifo = newFifo @PortBufSize 0 portRam $ bundle (ptxWritePush <$> atx, ptxReadPop <$> btx)
    baFifo = newFifo @PortBufSize 0 portRam $ bundle (ptxWritePush <$> btx, ptxReadPop <$> atx)
    arx = PortRx <$> fmap read baFifo <*> fmap notAlmostFull abFifo <*> register (Workload (0,0) 0 0) (fmap ptxWorkload btx)
    brx = PortRx <$> fmap read abFifo <*> fmap notAlmostFull baFifo <*> register (Workload (0,0) 0 0) (fmap ptxWorkload atx)
{-

  | H1 |     ptxWritePush-->    | FIFO |     prxRead-->     | H2 |
  |    |   <--prxWriteReady     |  PL  |  <--ptxReadPop     |    |
  |    |                                                    |    |
  |    |   <--prxRead           | FIFO |  <--ptxWritePush   |    |
  |    |      ptxReadPop-->     |  LP  |  ptxWriteReady-->  |    |

-}

-- A port connector that is resiliant to larger latencies, for SLR crossings.
-- FIFOs are placed at either side, providing backpressure. Pushes and pops are
-- delayed `latency` cycles and sent to the farside FIFO. This is sufficient
-- since push/pop signals need to make a full round trip before the nearside
-- FIFO will get popped and become ready again.
slrConnector
  :: (HiddenClockResetEnable dom, KnownNat latency)
  => SNat latency -> Signal dom PortTx -> Signal dom PortTx -> (Signal dom PortRx, Signal dom PortRx)
slrConnector latency atx btx = (arx, brx)
  where
    itrs = addSNat latency d1
    portRam = blockRam1 ClearOnReset (SNat @PortBufSize) Nothing

    aWPushZ = last $ iterate itrs (register Nothing) (ptxWritePush <$> atx)
    bRPopZ  = last $ iterate itrs (register False) (ptxReadPop <$> btx)
    azFifo = newFifo @PortBufSize 0 portRam $ bundle (ptxWritePush <$> atx, bRPopZ)
    zbFifo = newFifo @PortBufSize 0 portRam $ bundle (aWPushZ, ptxReadPop <$> btx)

    bWPushZ = last $ iterate itrs (register Nothing) (ptxWritePush <$> btx)
    aRPopZ  = last $ iterate itrs (register False) (ptxReadPop <$> atx)
    bzFifo = newFifo @PortBufSize 0 portRam $ bundle (ptxWritePush <$> btx, aRPopZ)
    zaFifo = newFifo @PortBufSize 0 portRam $ bundle (bWPushZ, ptxReadPop <$> atx)

    arx = PortRx <$> fmap read zaFifo <*> fmap notAlmostFull azFifo <*> last (iterate itrs (register (Workload (0,0) 0 0)) (fmap ptxWorkload btx))
    brx = PortRx <$> fmap read zbFifo <*> fmap notAlmostFull bzFifo <*> last (iterate itrs (register (Workload (0,0) 0 0)) (fmap ptxWorkload atx))

-- A set of 2D-meshes spread across multiple SLRs. After `d` each rows, extra
-- registers are inserted to facilitate the long wires crossing SLR boundaries.
--
genSuperMesh
  :: forall n m d
   . (HiddenClockResetEnable DomIn, KnownNat n, KnownNat m, KnownNat d)
  => SNat (d+1)
  -> Signal DomIn (Maybe TemplAddr) -- ^ Root PE Go signal
  -> Signal DomIn Bool -- ^ Unlock/enable signal
  -> Signal DomIn (RamOp RomSize Template) -- ^ PE Code
  -> Signal DomIn HeapAddr -- ^ GC Threshold
  -> PEMesh DomIn (n+1) ((d+1)*(m+1))
genSuperMesh _ go unlock code gcThres = dfold prx appendMesh singletonMesh (repeat submesh)
  where
  prx = Proxy :: Proxy (AppendMesh DomIn (n+1) (m+1))

  -- A master PE that accepts external `go` and reports its final results/stats
  singletonMesh :: AppendMesh DomIn (n+1) (m+1) @@ 0
  singletonMesh = genMesh (pure 0) go unlock code gcThres

  submesh :: Signal DomIn (Index MaxPERows) -- ^ Y-offset for this submesh
          -> PEMesh DomIn (n+1) (m+1)
  submesh yOff = genMesh yOff (pure Nothing) dRelease dCode dGcThreshold
  dRelease = last $ iterate (SNat @MaxPECols) (register False) unlock
  dCode = last $ iterate (SNat @MaxPECols) (register RamNoOp) code
  dGcThreshold = last $ iterate (SNat @MaxPECols) (register 0) gcThres

-- Append a row of PEs onto the bottom of a PEMesh
appendMesh
  :: forall dom l n m
   . (HiddenClockResetEnable dom, KnownNat m)
  => SNat l -> (Signal dom (Index MaxPERows) -> PEMesh dom (n+1) (m+1)) -> PEMesh dom (n+1) ((l+1)*(m+1)) -> PEMesh dom (n+1) ((l+2)*(m+1))
appendMesh y sb sp usRx rsRx dsRx lsRx = (usTx, rsTx, dsTx, lsTx, ret, stats)
  where
    spHeight = mulSNat (addSNat y d1) (SNat @(m+1))
    -- Apply to sbmesh
    (newUsTx, newRTx, newDsTx, newLTx, _, _) =
      sb (pure $ snatToNum spHeight)
        spToSb (drop spHeight rsRx) dsRx (drop spHeight lsRx)

    -- Apply to spermesh
    (meshUsTx, meshRsTx, meshDsTx, meshLsTx, ret, stats) =
      sp usRx (take spHeight rsRx) sbToSp (take spHeight lsRx)

    -- Apply to new row
    (sbToSp, spToSb) =
      unzip $ zipWith (slrConnector d1) meshDsTx newUsTx

    -- Collect for top level
    (usTx, rsTx, dsTx, lsTx) =
      ( meshUsTx
      , meshRsTx ++ newRTx
      , newDsTx
      , meshLsTx ++ newLTx
      )
