{-# LANGUAGE AllowAmbiguousTypes  #-}
{-# LANGUAGE ApplicativeDo        #-}
{-# LANGUAGE FlexibleContexts     #-}
{-# LANGUAGE FlexibleInstances    #-}
{-# LANGUAGE LambdaCase           #-}
{-# LANGUAGE NumericUnderscores   #-}
{-# LANGUAGE RecordWildCards      #-}
{-# LANGUAGE ScopedTypeVariables  #-}
{-# LANGUAGE UndecidableInstances #-}
{-# OPTIONS_GHC -fno-warn-unused-top-binds #-} -- Unused things generated by `createDomain`
{-# OPTIONS_GHC -fno-warn-orphans #-} -- Unused things generated by `createDomain`

module Heron.PE
  ( heronPE
  , heronPE'
  , PortRx(..)
  , PortTx(..)
  , PEIn(..)
  , PEOut(..)
  , heronSingleCore
  , DomIn
  ) where

import           Barbies.TH
import           Clash.Annotations.TH
import           Clash.Prelude                         hiding (read)
import qualified Clash.Prelude.Testbench               as TB
import           Control.Lens                          hiding (Index, assign,
                                                        at, imap, op, (:>))
import           Data.Maybe                            (fromJust, fromMaybe,
                                                        isJust)

import           Heron.Core.Collector
import           Heron.Core.Core
import           Heron.Core.Fifo
import           Heron.Core.Heap
import           Heron.Core.ParStack
import           Heron.Core.SnoopStack
import           Heron.Core.Stack
import           Heron.Core.Types
import           Heron.Error
import           Heron.Parameters
import           Heron.Primitives.DualPortRam
import qualified Heron.Primitives.ReadFirstDualPortRam as RF
import           Heron.Schedule
import           Heron.Schedule.Types
import           Heron.Template
import           RetroClash.Barbies

data PortRx = PortRx
  { prxRead       :: Maybe ComMsg
  , prxWriteReady :: Bool
  , prxWorkload   :: Workload
  }
  deriving (Generic, NFDataX, Show, ShowX, BitPack, AutoReg)
data PortTx = PortTx
  { ptxWritePush :: Maybe ComMsg
  , ptxReadPop   :: Bool
  , ptxWorkload  :: Workload
  }
  deriving (Generic, NFDataX, Show, ShowX, BitPack, AutoReg)

declareBareB [d|
  data PEIn = PEIn
    { peGo :: Maybe TemplAddr
    -- ^ Signal to start evaluation at given template address
    , peRelease :: Bool
    -- ^ Signal to other PEs that evaluation can begin
    , peCode :: RamOp RomSize Template
    -- ^ Interface into code memory
    , peGcThreshold :: HeapAddr
    -- ^ GC triggering threshold
    , pePortsRx :: Vec 4 PortRx
    -- ^ Received port signals
    , peId :: CoreId
    } |]
deriving instance Generic (Pure PEIn)
deriving instance NFDataX (Pure PEIn)
deriving instance Show    (Pure PEIn)
deriving instance ShowX   (Pure PEIn)

declareBareB [d|
  data PEOut = PEOut
    { _peResult  :: Maybe (Either Err Atom)
    , _peStats   :: CPUStats
    , _pePortsTx :: Vec 4 PortTx
    } |]
makeLenses ''PEOut
deriving instance Generic (Pure PEOut)
deriving instance NFDataX (Pure PEOut)
deriving instance Show    (Pure PEOut)
deriving instance ShowX   (Pure PEOut)

type DebugState = (Pure CPUIn, Pure CPUOut, Pure GCIn, Pure GCOut, Pure ComIn, Pure ComOut)

-- | A complete processing element with large debug state exposed
heronPE'
  :: forall dom
   . (HiddenClockResetEnable dom)
  => Signals dom PEIn
  -> Signals dom PEOut
heronPE' PEIn{..} = PEOut {..}
  where
    CPUOut{..} = cpu peId CPUIn{rcReady = _mutRCReady, ..}
    GCOut{..}  = gc  peId GCIn{rcReady = _gcRCReady, ..}
    ComOut{..} = com peId ComIn{..}

    (_peStats, _peResult') = unbundle result
    _peResult = (<|>) <$> (fmap Right <$> _peResult')
                      <*> (fmap Left  <$> errAny)

    -- Latch results to make interaction with VIO easier
    result = let capture = (isJust .snd <$> _result) -- .||. (isJust <$> peGo)
                 clear = isJust <$> peGo
             in register (unpack 0) $ mux clear (pure $ unpack 0) (mux capture _result result)
    _pePortsTx = zipWith3 PortTx
                   <$> _writePortsPush -- Ensure PE errors are evaluated
                   <*> _readPortsPop
                   <*> _writeWorkloads

    -- Memory structure primitives
    uStkRam    = dpRam @UStkSize @dom @Update UltraRam
    aStkRam    = blockRam1 ClearOnReset (SNat @AStkSize) Nothing
    pStkRam    = blockRam1 ClearOnReset (SNat @PStkSize) Nothing
    mutBufRam  = blockRam1 ClearOnReset (SNat @GCMutBufSize) Nothing
    heapRam = newHeap $ specialiseHeap heapConfig
                           (dpRam    @HeapSize @dom @HeapNode UltraRam   )
                           (RF.dpRam @HeapSize @dom @HeapNode RF.BlockRam)
    tmplRam = newHeap $    dpRam @RomSize  @dom @Template     BlockRam
    gcRam   = newHeap $ RF.dpRam @HeapSize @dom @GCNode    RF.BlockRam

    -- Memory instantiations
    -- * Dual-port RAMs
    heapIn  = heapRam heapOut'
    tmplIn  = head . read <$>  tmplRam tmplOut'
    gcMemIn = gcRam _gcMemOut
    -- * Stacks
    (uStkIn, uStkSnoopIn, ustkRet, ustkWarn) = newSnoopStack uStkRam (bundle (_uStkPush, _uStkPop)) _ustkSnoop
    aStkIn = newStack aStkRam $ bundle (_aStkPush, _aStkPop)
    pStkIn = newStack pStkRam $ bundle (_pStkPush, _pStkPop)
    vStkIn = newCachedParStack _vStkOut _stkSnoopAddr
    mutUpdateIn = newFifo 0 mutBufRam (bundle (mutUpdatePush, _mutUpdatePop))
    comUpdateIn = newFifo 0 mutBufRam (bundle (comUpdatePush, _comUpdatePop))
    -- TODO Want a counter to latch between mut coms and com muts. Where do we put this signal afterwards to allow tracing?

    -- Shared memory arbitration
    -- * Heap shared between mut, com, and gc
    wrAddr op = case op of
                      RamWrite a _ -> Just a
                      _            -> Nothing
    isNoOp RamNoOp = True
    isNoOp _       = False

    -- heapOut' = heapOut''
    assertWritePos xs = fold (||) (map (isJust . wrAddr) xs) && isNoOp (head xs)
    heapOut' = TB.assert "Check for heap com clobbering"
      (fmap (isJust . wrAddr) _heapComOut .&&. comAccess .&&. (
          fmap wrAddr _heapComOut .==. register Nothing (wrAddr . head <$> _heapOut) .||.
          fmap wrAddr _heapComOut .==. register Nothing (wrAddr . last <$> _heapOut))
      )
      (pure False) $ TB.assert "Check for heap mut writing positions"
      (assertWritePos <$> _heapOut) -- If the mut is writing, then port A must be busy
      (pure False)
      heapOut''
    (heapOut'', gcAccess, comAccess, errHeap) = unbundle $ liftA3 arbitrateHeap _heapOut (maybe RamNoOp RamRead <$> _heapMemOut) _heapComOut
    -- * Code memory shared between mut and external interface
    tmplOut' = bundle $ (RamRead <$> _tmplOut) :> peCode :> Nil

    -- Error handling
    errPush = register Nothing $ fold (<|>) <$>
      bundle (_errMut :> _errGc :> errHeap :> errUpd :> Nil)


    -- If the mutator performs an update, ensure that it is overwriting a redex.
    errUpd = let reducing = register False $ -- Now it's current phase
                              (==Reduce) <$> _mutPhase -- This is really the next phase.
                 updValid SOut{..} = let u = fromJust _top
                                     in isJust (uAddr u) && not (uRoot u)
                 upd = register False $ -- Now it's prev phase
                         _uStkPop .&&. -- We need to have popped
                         updValid <$> uStkIn .&&.
                         reducing -- and currently be reducing (ignores any suspend pops)
                 bad = upd .&&. (isWHNF . head . read) <$> heapIn
             in mux bad (pure $ Just ErrMutDoubleUpdate) (pure Nothing)
            -- TODO I think we can reflow this by matching on Release?

    getFail (Just (CMFail _ e)) = Just e
    getFail _                   = Nothing
    errRx = getFail <$> schedCmd
    errAny = register Nothing $ liftA2 (<|>) errPush errRx

    -- Additional mutator inputs
    coreId = peId
    unlock = peRelease
    gcCmd     = register NoCmd   _cmd
    schedCmd = liftA2 (<|>) (fmap (CMFail (0,0)) <$> errAny) schedCmd'
    -- ^ Splice local errors so we can see them in simulation traces
    schedCmd' = _next <$> newFifo @2 0
      (blockRam1 ClearOnReset d2 Nothing)
      (bundle (_comMutRequest, _schedCmdPop))
    schedPause = not <$> _comMutReady
    nextAddrs = zipWith3 resolveNext
                  <$> fmap read gcMemIn
                  <*> autoReg (repeat (Nothing,Nothing)) _nextFree
                  <*> fmap allocd request
    begin  = let goRising (Just taddr) Nothing = Just (Fun 0 taddr True)
                 goRising _ _                  = Nothing
                 -- Version of peGo that only registers on rising Nothing to Just
                 go = goRising <$> peGo <*> register Nothing peGo
                 -- Want to clear go as soon as mutator starts reducing
                 ph = register Starting _mutPhase
                 clear = (==Reduce) <$> ph
                 -- Latch signal
                 latch = mux clear (pure Nothing) $
                   register Nothing (liftA2 (<|>) latch go)
             in  latch

    -- Additional collector inputs
    ustkIn = fromJust . _top <$> uStkSnoopIn
    mutSuspending = register False $ (==Suspend) <$> _mutPhase
    curTSO = register 0 _addrTSO
    rcNextRef = _next <$> newFifo @2 0
      (blockRam1 ClearOnReset d2 Nothing)
      (bundle (_gcNextRef, _rcRetPop))
    threadReady = _gcThreadReady
    threadRet = _next <$> newFifo @2 0
      (blockRam1 ClearOnReset d2 Nothing)
      (bundle (_gcThreadRet, _threadRetPop))

    heapMemIn = mux (register False gcAccess)
                  (Just . head . read <$> heapIn)
                  (pure Nothing)
    bubble       = register False _allocBubble
    triggerThres = register 0     peGcThreshold
    request = register RNothing $
              TB.assert "ERROR: Mutator allocating after bubble prediction"
                ( (fold (||) . allocd <$> _gcRequest) .&&. bubble )
                ( pure False ) -- We can never say we're bubbling the mutator and then do an allocation!
                _gcRequest
    stkIn = bundle (size <$> vStkIn, head . _snoops <$> vStkIn)

    -- Additional scheduler inputs
    priorityReset = isRising False unlock
    fetchUpdateReady = ( < maxBound - 1) . size <$> comUpdateIn
    gcThreadCmd = _threadCmd
    gcRCRequest = _rcCmd
    mutRCRequest = _rcReq
    heapComIn = mux (register False comAccess)
                  (Just . head . read <$> heapIn)
                  (pure Nothing)
    heapComReady = comAccess
    readPorts = map prxRead <$> pePortsRx
    writePortsReady = map prxWriteReady <$> pePortsRx
    readWorkloads = map prxWorkload <$> pePortsRx
    mutUpdate = let updateAddr u = case u of
                      Nothing           -> Nothing
                      Just (Enter  a _) -> Just a
                      Just (Modify   a) -> Just a
                      Just (Release  a) -> Just a
                in updateAddr <$> register Nothing _upd
    mutComRequest = register Nothing _schedRequest
    updRequest = let doRelease u rds = case u of
                       Just (Release _) -> blockee $ head (read rds)
                       _                -> Nothing
                 in liftA2 doRelease (register Nothing _upd) heapIn

    -- Mutation buffer helper
    -- Since we lock all node on entry, _that_'s the time we need to update, not during actual updates!
    -- Now we only pass updates that have a tsoAlloc with them... We really need to rename a bunch of stuff here.
    -- Core should signal if an update is just for Com or GC.
    -- tsoAlloc is abused for lots of other things too, that's an update signal too. PArt of the Core's update signal ADT?
    mutUpdatePush =
      let updBarrier = register False (isJust <$> _barrier)
          oldNode u = case u of
            Just (Enter _ n) -> Just n
            _                -> Nothing
      in mux updBarrier (oldNode <$> autoReg Nothing _upd) (pure Nothing)
    comUpdatePush =
      let updBarrier = isJust <$> _barrier
      -- This sort of bug (I didn't gate on WaitCmd before) makes me think that the WaitCmd should be a seperate signal for the mutator, leaving the barriers in place
      in mux updBarrier _fetchUpdatePush (pure Nothing)
    readyPoolNext = _readyPoolHead
    mutThreadCmd = _mutThreadCmd

    -- Allocation helpers
    resolveNext new current used = fromMaybe (tailPtr new)
                                             (if used then snd current else fst current)
    allocd (RAlloc as) = as
    allocd _           = repeat False

--------------------------------------------------------------------------------
-- Complete board-level systems

-- | A complete system with one heron core
heronSingleCore
  :: forall dom
   . (HiddenClockResetEnable dom)
  => Signals dom PEIn
  -> Signals dom PEOut
heronSingleCore PEIn{..} = undefined
{-
PEOut {..}
  where
    coreId = pure (0,0)
    CPUOut{..} = cpu coreId CPUIn{..}
    GCOut{..}  = gc  coreId GCIn{..}

    -- PE Outputs
    (_peStats, _peResult') = unbundle result
    _peResult = fmap Right <$> _peResult'
    -- Latch results to make interaction with VIO easier
    result = let capture = (isJust .snd <$> _result) .||. (isJust <$> peGo)
             in regEn (unpack 0) capture _result
    _pePortsTx = pure $ repeat (PortTx Nothing False $ Workload (0,0) 0 0)

    -- Memory structure primitives
    uStkRam    = blockRam1 ClearOnReset (SNat @UStkSize) Nothing
    aStkRam    = blockRam1 ClearOnReset (SNat @AStkSize) Nothing
    pStkRam    = blockRam1 ClearOnReset (SNat @PStkSize) Nothing
    mutBufRam  = blockRam1 ClearOnReset (SNat @GCMutBufSize) Nothing
    heapRam = newHeap $ specialiseHeap heapConfig
                           (dpRam    @HeapSize @dom @HeapNode UltraRam   )
                           (RF.dpRam @HeapSize @dom @HeapNode RF.BlockRam)
    tmplRam = newHeap $    dpRam @RomSize  @dom @Template    BlockRam
    gcRam   = newHeap $ RF.dpRam @HeapSize @dom @GCNode   RF.BlockRam

    -- Memory instantiations
    -- * Dual-port RAMs
    heapIn  = heapRam heapOut'
    tmplIn  = head . read <$>  tmplRam tmplOut'
    gcMemIn = gcRam _gcMemOut
    -- * Stacks
    uStkIn = newStack uStkRam $ bundle (_uStkPush, _uStkPop)
    aStkIn = newStack aStkRam $ bundle (_aStkPush, _aStkPop)
    pStkIn = newStack pStkRam $ bundle (_pStkPush, _pStkPop)
    vStkIn = newCachedParStack _vStkOut _stkSnoopAddr
    updateIn = newFifo 0 mutBufRam (bundle (updatePush, _updatePop))

    -- Shared memory arbitration
    -- * Heap shared between mut, com, and gc
    (heapOut', gcAccess, _, _) = unbundle $ liftA3 arbitrateHeap _heapOut (maybe RamNoOp RamRead <$> _heapMemOut) (pure RamNoOp)
    -- * Code memory shared between mut and external interface
    tmplOut' = bundle $ (RamRead <$> _tmplOut) :> peCode :> Nil

    -- Additional mutator inputs
    unlock = pure True
    gcCmd     = register NoCmd _cmd
    schedCmd  = pure Nothing
    schedPause = pure False
    nextAddrs = zipWith3 resolveNext
                  <$> fmap read gcMemIn
                  <*> register (repeat (Nothing,Nothing)) _nextFree
                  <*> fmap allocd request
    begin  = let rootAtom = fmap (flip (Fun 0) True) <$> peGo
                 -- capture  = (isJust <$> peGo) .||. (isJust . snd) <$> _result
             in  register Nothing rootAtom -- regEn Nothing capture rootAtom
                 -- Latching begin causes issues for root core when playing with context switching. Don't want it to repeat evaluation of `main`!
    readyPoolNext = pure Nothing

    -- Additional collector inputs
    ustkIn = pure $ Update Nothing 0 False False
    ustkRet = pure False
    ustkWarn = pure True
    mutSuspending = pure False
    curTSO = pure 0
    threadReady = pure True
    threadRet = pure $ Just $ TsoElem True Nothing -- TODO Surely that'll hang when we're waiting for the SparksElem result?
    rcReady = pure True
    rcNextRef = pure $ Just Nothing
    heapMemIn = mux (register False gcAccess)
                  (Just . head . read <$> heapIn)
                  (pure Nothing)
    bubble       = register False _allocBubble
    triggerThres = register 0     peGcThreshold
    request = register RNothing $
              TB.assert "ERROR: Mutator allocating after bubble prediction"
                ( (fold (||) . allocd <$> _gcRequest) .&&. bubble )
                ( pure False ) -- We can never say we're bubbling the mutator and then do an allocation!
                _gcRequest
    stkIn = bundle (size <$> vStkIn, head . _snoops <$> vStkIn)

    -- Mutation buffer helper
    updatePush = let updBarrier = isJust <$> _barrier
                     hasUpdate  = isJust <$> _updateAddr
                     trigger    = register False (updBarrier .&&. hasUpdate)
                 in mux trigger
                      (Just . head . read <$> heapIn)
                      (pure Nothing)

    -- Allocation helpers
    resolveNext new current used = fromMaybe (tailPtr new)
                                             (if used then snd current else fst current)
    allocd (RAlloc as) = as
    allocd _           = repeat False
-}

createDomain vXilinxSystem{vName="DomIn"  , vPeriod=  snatToNum (SNat @ClkT)}

-- | A complete processing element with large debug state exposed
heronPE
  :: HiddenClockResetEnable DomIn
  => "peIn"   ::: Signals DomIn PEIn
  -> "peOut"  ::: Signals DomIn PEOut
heronPE = heronPE'
{-# NOINLINE heronPE #-}
makeTopEntity 'heronPE
